# Generated by Django 4.0.3 on 2022-03-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_ch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project_ch',
            name='project_CHOICES',
            field=models.CharField(max_length=100),
        ),
    ]
