# Generated by Django 4.0.3 on 2022-03-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empdata', '0002_alter_project_ch_id_alter_project_ch_project_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_ch',
            name='project_CHOICES',
        ),
        migrations.AddField(
            model_name='project_ch',
            name='project',
            field=models.CharField(choices=[('RH', 'roadhow'), ('AT', 'avtracker'), ('CL', 'clara'), ('SA', 'streetai'), ('NF', 'ninetofive')], default='default value', max_length=100),
        ),
    ]
