# Generated by Django 4.0.3 on 2022-03-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empdata', '0003_remove_project_ch_project_choices_project_ch_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_ch',
            name='project',
            field=models.CharField(choices=[('RH', 'roadhow'), ('AT', 'avtracker'), ('CL', 'clara'), ('SA', 'streetai'), ('NF', 'ninetofive')], max_length=100),
        ),
    ]
