# Generated by Django 4.0.3 on 2022-03-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empdata', '0004_alter_project_ch_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_ch',
            old_name='project',
            new_name='project1',
        ),
    ]
