# Generated by Django 4.0.3 on 2022-03-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='emp_id',
            field=models.IntegerField(unique=True),
        ),
    ]
