# Generated by Django 4.0.3 on 2022-03-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_register_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='project',
            field=models.CharField(choices=[('RH', 'roadhow'), ('AT', 'avtracker'), ('CL', 'clara'), ('SA', 'streetai'), ('NF', 'ninetofive')], max_length=100),
        ),
    ]
