# Generated by Django 4.0.3 on 2022-04-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_datati'),
    ]

    operations = [
        migrations.AddField(
            model_name='datati',
            name='data1',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
